interface Tags {
    And: number,
    Basic: number,
    Break: number,
    Do: number,
    Else: number,
    Eq: number,
    False: number,
    Ge: number,
    Id: number,
    If: number,
    Index: number,
    Le: number,
    Minus: number,
    Ne: number,
    Num: number,
    Or: number,
    Real: number,
    Temp: number,
    True: number,
    While: number
}

export const Tags: Tags = {
    And: 256,
    Basic: 257,
    Break: 258,
    Do: 259,
    Else: 260,
    Eq: 261,
    False: 262,
    Ge: 263,
    Id: 264,
    If: 265,
    Index: 266,
    Le: 267,
    Minus: 268,
    Ne: 269,
    Num: 270,
    Or: 271,
    Real: 272,
    Temp: 273,
    True: 274,
    While: 275
}